// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Terminal_controller from "./terminal_controller";
application.register("terminal", Terminal_controller)

import LanguageSelectorController from "./language_selector_controller"
application.register("language-selector", LanguageSelectorController)
