// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Terminal_controller from "./terminal_controller";
application.register("terminal", Terminal_controller)

import LanguageSelectorController from "./language_selector_controller"
application.register("language-selector", LanguageSelectorController)

import DashboardDropdownController from "./dashboard_dropdown_controller"
application.register("dashboard-dropdown", DashboardDropdownController)

import "./selector_coordinator"

import NotificationsController from "./notifications_controller"
application.register("notifications", NotificationsController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import OnlineUsersController from "./online_users_controller"
application.register("online-users", OnlineUsersController)

import ConversationMessagesController from "./conversation_messages_controller"
application.register("conversation-messages", ConversationMessagesController)

import ConversationFormController from "./conversation_form_controller"
application.register("conversation-form", ConversationFormController)

import ClockController from "./clock_controller"
application.register("clock", ClockController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import SwalConfirmController from "./swal_confirm_controller"
application.register("swal-confirm", SwalConfirmController)

import SwalFlashController from "./swal_flash_controller"
application.register("swal-flash", SwalFlashController)

import LanguagesController from "./languages_controller"
application.register("languages", LanguagesController)

import LanguagesSearchController from "./languages_search_controller"
application.register("languages-search", LanguagesSearchController)

import TestimonialsCarouselController from "./testimonials_carousel_controller"
application.register("testimonials-carousel", TestimonialsCarouselController)

import CategoriesController from "./categories_controller"
application.register("categories", CategoriesController)

import CategoriesSearchController from "./categories_search_controller"
application.register("categories-search", CategoriesSearchController)


import BranchesPaginationController from "./branches_pagination_controller"
application.register("branches-pagination", BranchesPaginationController)

import UsersPaginationController from "./users_pagination_controller"
application.register("users-pagination", UsersPaginationController)

import RegistrationWizardController from "./registration_wizard_controller"
application.register("registration-wizard", RegistrationWizardController)
