// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Terminal_controller from "./terminal_controller";
application.register("terminal", Terminal_controller)

import LanguageSelectorController from "./language_selector_controller"
application.register("language-selector", LanguageSelectorController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import OnlineUsersController from "./online_users_controller"
application.register("online-users", OnlineUsersController)

import ConversationMessagesController from "./conversation_messages_controller"
application.register("conversation-messages", ConversationMessagesController)

import ConversationFormController from "./conversation_form_controller"
application.register("conversation-form", ConversationFormController)

import ClockController from "./clock_controller"
application.register("clock", ClockController)
