require 'rails_helper'

RSpec.feature 'SystemRoles', type: :feature do
  scenario 'admin creates a system role with Faker data' do
    visit new_system_role_path

    fill_in 'Name', with: Faker::Job.unique.position
    select 'system', from: 'Role type'
    select 'active', from: 'Status'
    fill_in 'Description', with: Faker::Lorem.sentence

    click_button 'Create System role'

    expect(page).to have_content(I18n.t('system_roles.create.success', locale: :es))
  end

  scenario 'admin sees list of roles generated by Faker' do
    create_list(:system_role, 5)

    visit system_roles_path

    SystemRole.find_each do |role|
      expect(page).to have_content(role.name)
    end
  end

  scenario 'admin deletes a role (soft delete)' do
    role = create(:system_role, name: Faker::Job.position)

    visit system_role_path(role)

    click_button 'Delete'

    role.reload
    expect(role.deleted_at).not_to be_nil
  end
end
