require 'rails_helper'

RSpec.feature 'SystemRoles', type: :feature do
  let!(:admin_role) do
    create(
      :system_role,
      name: 'Administrator',
      code: 'administrator',
      role_type: :system
    )
  end

  let!(:admin) do
    create(:user, :english).tap do |user|
      create(:user_role, user:, system_role: admin_role)
    end
  end

  before do
    sign_in admin
  end

  scenario 'admin sees list of roles generated by Faker' do
    create_list(:system_role, 5)

    visit system_roles_path

    SystemRole.available.find_each do |role|
      expect(page).to have_content(role.name)
    end
  end

  scenario 'admin sees permission toggles for a role' do
    role = create(:system_role, name: 'Cajero', code: 'cashier', role_type: :branch)
    permission = create(:permission, code: 'sales.access', name: 'Acceso a ventas', module_name: 'Ventas')
    create(:system_role_permission, system_role: role, permission:)

    visit system_role_path(role)

    expect(page).to have_content('Acceso a ventas')
    expect(page).to have_field("permission_#{permission.id}", checked: true)
  end

  scenario 'admin updates role permissions with toggles' do
    role = create(:system_role, name: 'Cajero', code: 'cashier', role_type: :branch)
    enabled = create(:permission, code: 'sales.access', name: 'Acceso a ventas', module_name: 'Ventas')
    disabled = create(:permission, code: 'inventory.access', name: 'Acceso a inventario', module_name: 'Inventario')
    create(:system_role_permission, system_role: role, permission: enabled)

    visit system_role_path(role)

    uncheck "permission_#{enabled.id}"
    check "permission_#{disabled.id}"
    click_button 'Save permissions'

    expect(role.reload.permissions).to contain_exactly(disabled)
    expect(page).to have_css(
      '[data-controller="swal-flash"][data-swal-flash-message-value="Role permissions were updated successfully."]',
      visible: :all
    )
  end
end
